### PR TITLE
_call: add rate limit to response data

### PR DESCRIPTION
**Pull request by arrabyte**
append response headers to returned data as rate limit info are inside headers.

### CODE REVIEW

**Review by caiusCitiriga — COMMENTED** [review]
Maybe it would be better to set this value in a place where the main REST api client could get it and expose a method on it to read the last value of these rate limits?

**Comment by arrabyte** [comment]
> Maybe it would be better to set this value in a place where the main REST api client could get it and expose a method on it to read the last value of these rate limits?

I don't think so as rate limit is related to a specific classes of APis, some have 10 calls for seconds other more. So store this data means keep a map of different rate limit for api. And also rate limit is an info that needs quick reaction, i mean i call the api, and I've ratelimit of 10 and status of 1, i should immediately slow the app.
 So maybe should be better provides specific field like rateLimit and rateLimitStatus in every response, likes in the old api (v2, v3).  The problem now is that not every call give back this info in the response headers, i don't know if bybit will introduce these info in the future. For this reason, for my app, at the moment i just add headers in the response and leaving at the application level the possibility to read the rate limit. I agree that after, when v5 api are better explained,  a refactoring should be a good idea.

**Comment by caiusCitiriga** [comment]
> > Maybe it would be better to set this value in a place where the main REST api client could get it and expose a method on it to read the last value of these rate limits?
> 
> I don't think so as rate limit is related to a specific classes of APis, some have 10 calls for seconds other more. So store this data means keep a map of different rate limit for api. And also rate limit is an info that needs quick reaction, i mean i call the api, and I've ratelimit of 10 and status of 1, i should immediately slow the app.
>  So maybe should be better provides specific field like rateLimit and rateLimitStatus in every response, likes in the old api (v2, v3).  The problem now is that not every call give back this info in the response headers, i don't know if bybit will introduce these info in the future. For this reason, for my app, at the moment i just add headers in the response and leaving at the application level the possibility to read the rate limit. I agree that after, when v5 api are better explained,  a refactoring should be a good idea.

My bad, I did not know about this diff on bybit. Sorry. What you say makes sense. I was having the binance SDK design in mind when I had written that comment

**Comment by tiagosiebler** [comment]
Thanks for the PR @arrabyte. As I said in the telegram community, initially I had the same thought as @caiusCitiriga. That’s also the design I took for binance, since they have a credits system where all api calls for diff endpoints compete for the total 1-minute allowance

but bybit is quite different (better!) here. Each endpoint has an independent rate limit, so it makes sense to track them independently. I've just released an implementation (#293) that is disabled by default, but once enabled, includes these bapi header states in the response. Take a look at the PR comments for examples on how it looks. 

To turn on the parser, just include the new setting in the RestClientV5 constructor:
```typescript
const client = new RestClientV5({
  parseAPIRateLimits: true,
});
```

Please let me know how you get on and if you notice any issues (although the mechanism is both very simple and protective). After some time, I may turn it on by default.

**Comment by arrabyte** [comment]
Thank you very much. I like this implementation, I'll test it as soon
as possible. Bye.

Il giorno lun 30 ott 2023 alle ore 15:44 Tiago
***@***.***> ha scritto:

**Pull request closed without merging**
